# Generated by Django 3.0.5 on 2020-04-08 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_published',
            new_name='datePublished',
        ),
    ]
