# Generated by Django 3.0.5 on 2020-04-15 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200407_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='body_text',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='byline',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='location',
            new_name='located',
        ),
        migrations.RemoveField(
            model_name='article',
            name='datePublished',
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(default='text', editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='article',
            name='versioncreated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
